# Generated by Django 4.2.7 on 2023-11-30 06:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='articles',
            name='keyword',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='articles',
            name='title',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='articles',
            name='topic',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='articles',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
    ]
