# Generated by Django 4.2.7 on 2023-11-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_articles_created_at_articles_keyword_articles_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='content',
            field=models.CharField(default='', max_length=100000000),
        ),
    ]
