# Generated by Django 4.2.7 on 2023-11-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_articles_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=models.CharField(default='', max_length=10000000000),
        ),
    ]
