# Generated by Django 4.2.7 on 2023-12-10 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0004_alter_articles_content'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='articles',
            table='articles',
        ),
    ]
